#pragma once
#define IN_MAX_LEN_TEXT 1024*1024   
#define IN_CODE_ENDL '\n'          


#define IN_CODE_TABLE {\
	/*ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T,\
	ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T,\
	ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T,\
	ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T,\
	ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T,\
	ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T,\
	ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T,\
	ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T,\
																																								   \
	ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T,\
	ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T,\
	ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T,\
	ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T,\
	ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T,\
	ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T,\
	ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T,\
	ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T,\*/\
	ININ::F, ININ::F, ININ::F, ININ::F, ININ::F, ININ::F, ININ::F, ININ::F, ININ::F, ININ::F, '|',     ININ::F, ININ::F, ININ::F, ININ::F, ININ::F,\
	ININ::F, ININ::F, ININ::F, ININ::F, ININ::F, ININ::F, ININ::F, ININ::F, ININ::F, ININ::F, ININ::F, ININ::F, ININ::F, ININ::F, ININ::F, ININ::F,\
	ININ::T, ININ::F, ININ::F, ININ::F, ININ::F, ININ::F, ININ::F, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::F, ININ::T,\
	ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::F, ININ::T, ININ::F, ININ::F, \
	ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, \
	ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, \
	ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, \
	ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, \
	\
	ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, \
	ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, \
	ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, \
	ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, \
	'-',     ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::I, ININ::T, ININ::T, \
	ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, \
	ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, \
	ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T, ININ::T  \
} 

namespace In
{
	struct ININ
	{
		enum { T = 1024, F = 2048, I = 4096 };
		int size;
		int lines;
		int ignor;
		unsigned char* text;
		int code[256];
	};
	ININ getin(wchar_t infile[]);
}